name: Build Android APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      # 1. Liberiamo spazio (Kivy occupa molto)
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false

      # 2. Prepariamo Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installiamo le dipendenze di sistema (quelle che servono a Buildozer)
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libffi-dev libssl-dev zip unzip autoconf libtool pkg-config

      # 4. Installiamo Buildozer e Cython (la versione giusta!)
      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.36

      # 5. Lanceremo la build e risponderemo "sì" automaticamente a tutto
      - name: Build with Buildozer
        run: |
          yes | buildozer android debug

      # 6. Carichiamo il file APK finale
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
